Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x7f9f7531f0>:
Traceback (most recent call last):
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 147, in peekaboo
    await interaction.response.defer()
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/interactions.py", line 694, in defer
    await adapter.create_interaction_response(
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/webhook/async_.py", line 204, in request
    raise NotFound(response, data)
nextcord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x7f9f7531f0>:
Traceback (most recent call last):
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 147, in peekaboo
    await interaction.response.defer()
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/interactions.py", line 694, in defer
    await adapter.create_interaction_response(
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/webhook/async_.py", line 204, in request
    raise NotFound(response, data)
nextcord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
contains your mom
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
i had sex.. BREEZE... f breeze
peekaboo
capturing gif
creating gif
done creating gif
i had sex.. BREEZE... NO MORE BREEZE WE WIN
i had sex.. *** BREEZE not enough time passed: 2294s ***
i had sex.. BREEZE... i think theyâ€™re making changes to bind and breeze
i had sex.. *** BREEZE not enough time passed: 2340s ***
peekaboo
capturing image
done capturing image
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 168
    break;
    ^
SyntaxError: 'break' outside loop
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 166
    choices = {5, 25, 75, 100, 150, 200}
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 319, in <module>
    GPIO.add_event_detect(12, GPIO.RISING, callback=light_callback)
NameError: name 'light_callback' is not defined
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
peekaboo
capturing image
done capturing image
peekaboo
peekaboo
peekaboo
peekaboo
capturing image
done capturing image
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
[vm.tiktok] ZMF4KMXo8: Downloading webpage
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
tiktok found in message
[TikTok] 7172287524054813957: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7172287524054813957: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7172287524054813957: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7172287524054813957: Downloading video feed
WARNING: [TikTok] 7172287524054813957: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7172287524054813957: Downloading webpage
[info] 7172287524054813957: Downloading 1 format(s): 0
[download] Destination: ./dltiktok.mp4
[download]   0.0% of    2.39MiB at  Unknown B/s ETA Unknown[download]   0.1% of    2.39MiB at  535.79KiB/s ETA 00:04  [download]   0.3% of    2.39MiB at    1.01MiB/s ETA 00:02[download]   0.6% of    2.39MiB at    1.91MiB/s ETA 00:01[download]   1.3% of    2.39MiB at    2.50MiB/s ETA 00:00[download]   2.6% of    2.39MiB at    2.35MiB/s ETA 00:00[download]   5.2% of    2.39MiB at    2.24MiB/s ETA 00:01[download]  10.4% of    2.39MiB at    3.13MiB/s ETA 00:00[download]  20.9% of    2.39MiB at    3.03MiB/s ETA 00:00[download]  41.7% of    2.39MiB at    3.30MiB/s ETA 00:00[download]  83.5% of    2.39MiB at    3.71MiB/s ETA 00:00[download] 100.0% of    2.39MiB at    4.00MiB/s ETA 00:00[download] 100% of    2.39MiB in 00:00:00 at 2.76MiB/s   
[vm.tiktok] ZMFVeTP7K: Downloading webpage
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
creating gif
done creating gif
tiktok found in message
[TikTok] 7170846916429810987: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7170846916429810987: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7170846916429810987: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7170846916429810987: Downloading video feed
WARNING: [TikTok] 7170846916429810987: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7170846916429810987: Downloading webpage
ERROR: [TikTok] 7170846916429810987: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[vm.tiktok] t: Downloading webpage
download error, most likely slide show
tiktok found in message
https://vm.tiktok.com/t/ZTR4Af3mg/
[TikTok] 7166763657446067498: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7166763657446067498: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7166763657446067498: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7166763657446067498: Downloading video feed
WARNING: [TikTok] 7166763657446067498: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7166763657446067498: Downloading webpage
[info] 7166763657446067498: Downloading 1 format(s): 0
[download] Destination: ./dltiktok.mp4
[download]   0.0% of    2.00MiB at  Unknown B/s ETA Unknown[download]   0.1% of    2.00MiB at    1.80MiB/s ETA 00:01  [download]   0.3% of    2.00MiB at    2.81MiB/s ETA 00:00[download]   0.7% of    2.00MiB at    4.09MiB/s ETA 00:00[download]   1.5% of    2.00MiB at    6.75MiB/s ETA 00:00[download]   3.1% of    2.00MiB at    2.58MiB/s ETA 00:00[download]   6.2% of    2.00MiB at    2.64MiB/s ETA 00:00[download]  12.4% of    2.00MiB at    3.19MiB/s ETA 00:00[download]  24.9% of    2.00MiB at    3.81MiB/s ETA 00:00[download]  49.9% of    2.00MiB at    4.64MiB/s ETA 00:00[download]  99.9% of    2.00MiB at    5.19MiB/s ETA 00:00[download] 100.0% of    2.00MiB at    5.16MiB/s ETA 00:00[download] 100% of    2.00MiB in 00:00:00 at 4.06MiB/s   
[vm.tiktok] t: Downloading webpage
peekaboo
peekaboo
peekaboo
contains your mom
peekaboo
peekaboo
peekaboo
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
FEET... lucas r u kickin ur feet in the air rn
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
tiktok found in message
https://vm.tiktok.com/t/ZTR4PnMuP/
[TikTok] 7162019404065099050: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7162019404065099050: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7162019404065099050: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7162019404065099050: Downloading video feed
WARNING: [TikTok] 7162019404065099050: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7162019404065099050: Downloading webpage
[info] 7162019404065099050: Downloading 1 format(s): 0
[download] Destination: ./dltiktok.mp4
[download]   0.1% of    1.68MiB at   87.18KiB/s ETA 00:19[download]   0.2% of    1.68MiB at  241.49KiB/s ETA 00:07[download]   0.4% of    1.68MiB at  531.94KiB/s ETA 00:03[download]   0.9% of    1.68MiB at    1.04MiB/s ETA 00:01[download]   1.8% of    1.68MiB at    1.75MiB/s ETA 00:00[download]   3.7% of    1.68MiB at    1.31MiB/s ETA 00:01[download]   7.4% of    1.68MiB at  889.34KiB/s ETA 00:01[download]  14.8% of    1.68MiB at    1.25MiB/s ETA 00:01[download]  29.7% of    1.68MiB at    1.10MiB/s ETA 00:01[download]  59.4% of    1.68MiB at  581.97KiB/s ETA 00:01[download]  82.1% of    1.68MiB at  622.70KiB/s ETA 00:00[download] 100.0% of    1.68MiB at  502.20KiB/s ETA 00:00[download] 100% of    1.68MiB in 00:00:03 at 483.60KiB/s 
[vm.tiktok] t: Downloading webpage
['<@351213875770949633>']
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
['<@351213875770949633>']
peekaboo
capturing image
done capturing image
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing image
done capturing image
tiktok found in message
https://vm.tiktok.com/t/ZTR4Hr4Fk/
[TikTok] 7163373216432475435: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7163373216432475435: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7163373216432475435: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7163373216432475435: Downloading video feed
WARNING: [TikTok] 7163373216432475435: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7163373216432475435: Downloading webpage
[info] 7163373216432475435: Downloading 1 format(s): 0
[download] Destination: ./dltiktok.mp4
[download]   0.1% of    1.50MiB at   61.92KiB/s ETA 00:24[download]   0.2% of    1.50MiB at  174.84KiB/s ETA 00:08[download]   0.5% of    1.50MiB at  389.40KiB/s ETA 00:03[download]   1.0% of    1.50MiB at  797.90KiB/s ETA 00:01[download]   2.0% of    1.50MiB at    1.40MiB/s ETA 00:01[download]   4.1% of    1.50MiB at    2.30MiB/s ETA 00:00[download]   8.3% of    1.50MiB at    2.22MiB/s ETA 00:00[download]  16.6% of    1.50MiB at    1.89MiB/s ETA 00:00[download]  33.2% of    1.50MiB at    2.62MiB/s ETA 00:00[download]  66.5% of    1.50MiB at    2.94MiB/s ETA 00:00[download] 100.0% of    1.50MiB at    3.03MiB/s ETA 00:00[download] 100% of    1.50MiB in 00:00:00 at 1.97MiB/s   
[vm.tiktok] t: Downloading webpage
contains your mom
contains your mom
peekaboo
peekaboo
capturing image
done capturing image
peekaboo
peekaboo
tiktok found in message
https://vm.tiktok.com/t/ZTR4Qc7vF/
[TikTok] 7171938188972395782: Downloading video feed
ERROR: [TikTok] 7171938188972395782: Requested format is not available. Use --list-formats for a list of available formats
download error, most likely slide show
peekaboo
['willem']
['<@351213875770949633>']
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing gif
creating gif
done creating gif
[ WARN:0@98.009] global /io/opencv/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x7f81d219a0>:
Traceback (most recent call last):
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 197, in peekaboo
    frames.append(rescale_frame(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB), percent=scale_by))
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing gif
creating gif
done creating gif
peekaboo
capturing gif
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x7f94040e50>:
Traceback (most recent call last):
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 209, in peekaboo
    await interaction.send(file=nextcord.File('./dancemonkeydance.gif'))
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/interactions.py", line 571, in send
    return await self.followup.send(
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/webhook/async_.py", line 1527, in send
    data = await adapter.execute_webhook(
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/webhook/async_.py", line 157, in request
    async with session.request(
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/ootami/dev/smirkcat/smirkcat.py", line 211, in peekaboo
    await interaction.send(content='file probably too big', ephemeral=True)
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/nextcord/webhook/async_.py", line 157, in request
    async with session.request(
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/ootami/envs/mm/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2745)

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2745)
Logged in as Meow Meow ðŸ™€#6007
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: bot testing ###
### LOGGED IN AS Meow Meow ðŸ™€#6007, guild: i had sex.. ###
peekaboo
capturing gif
creating gif
done creating gif
